### PR TITLE
Add list of directory implementations

### PR DESCRIPTION
**Pull request by farshidtz**
See https://github.com/w3c/wot-discovery/pull/225/files

### CODE REVIEW

**Comment by farshidtz** [comment]
I think the given template is not so informative. I prefer something like:

| Organization | Name | License | Language | APIs |
|---|---|---|---|---|
| Fraunhofer | LinkSmart Thing Directory | Apache 2 | Go | Registration, Notification, Search (JSONPath, XPath) |
| UPM | WoTHive |  |  |  |
| Siemens | Logilab TDD |  |  |  |

What do others think?
@wiresio @AndreaCimminoArriaga

**Comment by AndreaCimminoArriaga** [comment]
Sounds good to me. Please Farshid could you please add this info to the WoTHive Apache 2, Java, Introduction (well-known URIs), Registration, Notification, Search (JSONPath, SPARQL)

**Comment by farshidtz** [comment]
Done.

> Introduction (well-known URIs)

This is technically not part of the directory APIs. There is another section for introduction mechanisms in the same file.

**Comment by wiresio** [comment]
Also good for me - maybe add _database_:
- License: not open source
- Language: Python
- Database: Apache Jena Fuseki
- (Current) APIs: Registration, Search (SPARQL)

**Comment by farshidtz** [comment]
@wiresio do you also have a link to the component description? It could be a product page or another local .md file.

> maybe add _database_

Not sure about this. I feel it is too technical and could be confusing if more than one DB is used, e.g. one for TDs, another for caching events or indexing TDs. Let's discuss on Monday.

**Pull request merged**
