### PR TITLE
Refactor Directory Service API TD (split events) 

### PR DESCRIPTION
**Pull request by farshidtz**
This PR takes events-splitting parts of #184. 
 
In addition:
- [x] Add back `full` URI variable
- [x] Rename `full` to `diff`
- [x] Revert event type values; needs further discussion: #197
- [x] Rename affordance names to nouns: `thingCreation`, `thingUpdate`, `thingDeletion`
- [x] Updates the text to reflect these changes

***
<a href="https://pr-preview.s3.amazonaws.com/farshidtz/wot-discovery/pull/196.html" title="Last updated on Jun 5, 2021, 5:18 PM UTC (8ccc0ff)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-discovery/196/89e9932...farshidtz:8ccc0ff.html" title="Last updated on Jun 5, 2021, 5:18 PM UTC (8ccc0ff)">Diff</a>

### CODE REVIEW

**Comment by farshidtz** [comment]
@benfrancis, it would be great to have your opinion on renaming affordance names to nouns: `thingCreation`, `thingUpdate`, `thingDeletion`.

**Comment by farshidtz** [comment]
I now thinking of taking the path style from #159. There is indeed a way to follow that and at the same time allow subscription to all:

So, the current API:
```
/events{?type,diff}
```
e.g. expansion:
* `/events?type=create&diff=true` one event
* `/events?diff=true` all events

would follow #159 and become:
```
/events{/type}{?diff}
```
e.g. expansion:
* `/events/create?diff=true` one event
* `/events?diff=true` all events

**Comment by benfrancis** [comment]
> @benfrancis, it would be great to have your opinion on renaming affordance names to nouns: `thingCreation`, `thingUpdate`, `thingDeletion`.

Sure, https://github.com/w3c/wot-discovery/issues/197#issuecomment-854079411

**Comment by farshidtz** [comment]
This PR is now ready for review.
 
After these changes, the text has become a bit confusing. We have to rewrite some parts in future to improve.

I have created a separate PR for the change in the URI template explained in my comment above: https://github.com/w3c/wot-discovery/pull/198

**Pull request merged**
