### PR TITLE
Update SPARQL DDoS ed note

### PR DESCRIPTION
**Pull request by mmccool**
Tweak ed note; please check

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-discovery/pull/107.html" title="Last updated on Jan 26, 2021, 12:17 AM UTC (8a4bfb4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-discovery/107/349b8fc...8a4bfb4.html" title="Last updated on Jan 26, 2021, 12:17 AM UTC (8a4bfb4)">Diff</a>

### CODE REVIEW

**Comment by AndreaCimminoArriaga** [comment]
I agree with the note, except for this part "or complexity of queries". I think that the complexity of a query should not be considered as a security thread. Maybe can we remove this part?

**Comment by mmccool** [comment]
Complexity of queries is a security threat because it can be used for a DDoS attack, e.g. submitting a query that takes a pathological amount of time to complete to tie up the server.   This is also applicable to JSONpath to some extent.   So it applies to all query types, not just SPARQL, so we can cover it under "Security and Privacy Considerations" where mitigations can be mentioned (e.g. watchdog timers).

**Comment by mmccool** [comment]
To Do: move DDoS discussion and mitigation to "Security and Privacy Considerations".   See also https://github.com/w3c/wot-security/issues/196 which will be discussed in the WoT Security meeting, so it would be good to mention possible security concerns there.

**Comment by mmccool** [comment]
Updated to move DDoS discussion to S&PC section.   Other considerations should be added later.

**Pull request merged**
