### PR TITLE
Describe the information model

### LINKED ISSUE #34: Add links section to directory information model
See also https://github.com/w3c/wot-discovery/issues/32

It has been suggested that in some cases we want to store links to TDs or to other directories in a directory rather than just TDs.  We have two possible ways to do this:
1. Store TDs with just links (note the interactions, etc. in a TD are optional, so...) 
2. Have a separate links section in the information model of the directory.

Both are actually useful.  Option 1 can be used if searchable metadata, eg. semantic annotation, is needed (eg for a remote directory where we want to list the types of Things indexed by that directory).  But option 2 is also simple and useful, and can do things like have concrete links to all TDs stored on the directory, as well as links to self-identifying devices that for some reason (eg private information in the TD) don't want to store a copy of their TD in the directory.   Note that links may be to both other information stored in the directory itself and to remote information (eg other directories).

The links section should probably have some metadata, i.e. at least a relation type (probably the same as the relation types we need to define for DID documents, and able at least to distinguish things from directories), and maybe also an optional spatial location or region (to facilitate federated  spatial queries over a distributed directory service).   But any more than that, and a TD should be used.

### PR DESCRIPTION
**Pull request by farshidtz**
- [x] Conceptual class diagram (related to #98)
- [x] Directory type (related to #54)
- [x] Link type and example (closes #34)
- [x] Discovery context (related to #54)
- [x] Example for tdd:registration extension (related to #98 and #30)
- [x] ~~API specification and description for TD enrichment with registration info~~ Added ednote, will cover in another PR.

The preview doesn't show the figure. I'll add it here (more recent diagrams below):

***
<a href="https://pr-preview.s3.amazonaws.com/farshidtz/wot-discovery/pull/112.html" title="Last updated on Feb 1, 2021, 4:35 PM UTC (5c2480d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-discovery/112/52a3a5f...farshidtz:5c2480d.html" title="Last updated on Feb 1, 2021, 4:35 PM UTC (5c2480d)">Diff</a>

### CODE REVIEW

**Comment by AndreaCimminoArriaga** [comment]
I like the model, however I would change the types names for others since right now they seem a bit confusing to me. Maybe Directory, Thing Description, Directory Description, and Link Description ?

**Comment by farshidtz** [comment]
> I like the model, however I would change the types names for others since right now they seem a bit confusing to me. Maybe Directory, Thing Description, Directory Description, and Link Description ?

I like the suggested naming. After some discussion with @AndreaCimminoArriaga, here is a new diagram:

**Comment by farshidtz** [comment]
Added Thing for self-described devices; the model is also relevant to those.

**Review by AndreaCimminoArriaga — APPROVED** [review]

**Comment by farshidtz** [comment]
After a discussion with @AndreaCimminoArriaga, updated the type in directory API's TD and added annotations and arrowheads to diagram.

**Pull request merged**
